// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCMlDbneQAvN_D0E3P8iHCKHg-_LNSmI',
    appId: '1:812338479385:web:6285ee55fab28ffbcb4588',
    messagingSenderId: '812338479385',
    projectId: 'login-d742a',
    authDomain: 'login-d742a.firebaseapp.com',
    storageBucket: 'login-d742a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHGtvaBL0X3YOLwRzBJCWInNcNfFqDko',
    appId: '1:812338479385:android:33ced50b80ae6f02cb4588',
    messagingSenderId: '812338479385',
    projectId: 'login-d742a',
    storageBucket: 'login-d742a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZtU_uvNbM2xloMnzU7_fUk20ymbUEEg0',
    appId: '1:812338479385:ios:4b36b26688f65114cb4588',
    messagingSenderId: '812338479385',
    projectId: 'login-d742a',
    storageBucket: 'login-d742a.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZtU_uvNbM2xloMnzU7_fUk20ymbUEEg0',
    appId: '1:812338479385:ios:4b36b26688f65114cb4588',
    messagingSenderId: '812338479385',
    projectId: 'login-d742a',
    storageBucket: 'login-d742a.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFCMlDbneQAvN_D0E3P8iHCKHg-_LNSmI',
    appId: '1:812338479385:web:2712824c722984bbcb4588',
    messagingSenderId: '812338479385',
    projectId: 'login-d742a',
    authDomain: 'login-d742a.firebaseapp.com',
    storageBucket: 'login-d742a.firebasestorage.app',
  );

}